### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError ?

### ISSUE THREAD

**Issue by kendrick-k** [QubitProducts/opentag-library-sdk#46]
shared/bin/build.sh libraries/library 

Writing results...
,shared/js/tagsdk-current.js
,libraries/library/library/v1/Tag.js
 === Done in: 0.034278784s === 

Exception in thread "main" java.lang.NoSuchMethodError: java.nio.file.Files.write(Ljava/nio/file/Path;Ljava/lang/Iterable;[Ljava/nio/file/OpenOption;)Ljava/nio/file/Path;
	at com.qubitproducts.compilejs.fs.CFile.saveString(CFile.java:530)
	at com.qubitproducts.compilejs.CompileJS.compile(CompileJS.java:829)
	at com.qubitproducts.compilejs.CompileJS.main(CompileJS.java:268)
	at librarywizard.Build.run(Build.java:88)
	at librarywizard.Main.main(Main.java:176)

**Comment by kendrick-k** [comment]
Failed to load: /shared/bin/html/js/build-location.js Exception: SyntaxError: Unexpected token <

**Comment by peterfronc** [comment]
Please update your java to higher version (with NIO support).

**Comment by kendrick-k** [comment]
Cool indeed Java 8 (instead of 7) : you should add it to the readme ! Thanks

**Comment by peterfronc** [comment]
Plenty of things gettting updated, readme as well. Thanks ;-)
